# This Docker Compose is meant to be used for development and local testing purposes

services:
  agv-app-map-store-service:
    image: agv-app-map-store-service
    container_name: agv-app-map-store-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug # Debug or Release (defaults to Release in Dockerfile)
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - agv-app-map-store-service-data:/app/data

volumes:
  agv-app-map-store-service-data: